/**
 * @generated by tools/gen-crown-assets.mjs — do not edit by hand.
 * Inline SVG artwork for the ten crown tiers, sourced from assets/crown_*.svg
 * (keys match the CROWN_LEVELS ids in src/crowns.ts).
 */
export declare const CROWN_SVGS: Readonly<Record<string, string>>;
//# sourceMappingURL=crownAssets.d.ts.map